import Head from 'next/head'
import { BsFillMoonStarsFill, BsTerminalFill, BsLink45Deg, BsMedium } from 'react-icons/bs';
import { AiFillLinkedin, AiFillGithub, AiFillMail } from 'react-icons/ai';
import { FaGraduationCap } from 'react-icons/fa'
import { MdArticle, MdOutlineArticle } from 'react-icons/md'
import { GrAppleAppStore } from 'react-icons/gr'
import Image from 'next/image';
import { useState } from 'react';


export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Aviral Mehrotra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-zinc-800'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl text-zinc-800 dark:text-slate-200'>aviral<span className="text-zinc-500 dark:text-zinc-400">mehrotra</span></h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}  className='cursor-pointer text-2xl text-zinc-800 dark:text-slate-200'/>
              </li>
              <li><a className='bg-gradient-to-r from-cyan-600 to-cyan-400 text-white px-4 py-2 rounded-md ml-8' href="resume.pdf" download="Aviral Mehrotra's Resume">Resume</a></li>
            </ul>
          </nav>
          <div className='relative w-1 h-1 md:w-20 md:h-20'>
            <Image />
          </div>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-cyan-400 font-medium md:text-7xl lg:text-9xl'>
              Aviral Mehrotra
            </h2>
            <h3 className='text-2xl py-5 md:text-4xl dark:text-gray-200'>
              Student and Software Developer
            </h3>
            <p className='text-md py-1 leading-8 text-gray-800 md:text-2xl max-w-lg mx-auto dark:text-slate-200'>
              High school student interested in computer science,
              AI and machine learning, economics, and emerging technologies.
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-200'>
            <a target="_blank" href="https://github.com/aviral-mehrotra" rel="noopener noreferrer"><AiFillGithub /></a>
            <a target="_blank" href="https://www.linkedin.com/in/aviralmehrotra" rel="noopener noreferrer"><AiFillLinkedin /></a>
            <a target="_blank" href="https://medium.com/@aviral.mehrotra" rel="noopener noreferrer"><BsMedium /></a>
            <a href="mailto:aviral.mehrotra@gmail.com" rel="noopener noreferrer"><AiFillMail /></a>
          </div>
        </section>
        
        <section className='min-h-screen'>

          <div className='text-center'>
            <h3 className='text-2xl md:py-5 md:pt-10 md:text-4xl dark:text-gray-200'>
              Information
            </h3>
          </div>
          
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 bg-slate-50 flex-1'>
              <FaGraduationCap className='text-7xl w-full'/>
              <h3 className='text-xl font-bold pt-8 pb-2'>Student</h3>
              <p className='py-2'>
                I am currently a high school senior with a passion for computer science.
                I am looking to major in computer science and economics in college.
              </p>
              <h4 className='py-4 text-teal-600'>Notable Classes</h4>
              <p className='text-gray-800 py-1'>AP Computer Science A</p>
              <p className='text-gray-800 py-1'>AP Calculus BC</p>
              <p className='text-gray-800 py-1'>AP Statistics</p>
              <p className='text-gray-800 py-1'>AP Physics C: Mechanics</p>
              <p className='text-gray-800 py-1'>AP Physics C: Electricity and Magnetism</p>
              <p className='text-gray-800 py-1'>Payton Advanced Studies Cohort (PASC)</p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10 bg-slate-600 flex-1'>
              <BsTerminalFill className='text-7xl text-slate-200 w-full'/>
              <h3 className='text-xl font-bold pt-8 pb-2 text-slate-50'>Developer</h3>
              <p className='text-slate-200 py-2'>
                I started coding in my first year of high school and have interned
                at tech startups and Fermilab, won several hackathons, and tutored other students.
              </p>
              <h4 className='py-4 text-teal-600'>Languages and Technologies</h4>
              <p className='text-slate-200 py-1'>Python</p>
              <p className='text-slate-200 py-1'>C++</p>
              <p className='text-slate-200 py-1'>Swift + Xcode</p>
              <p className='text-slate-200 py-1'>React + Tailwind CSS</p>
              <p className='text-slate-200 py-1'>Google Cloud Functions</p>
              <p className='text-slate-200 py-1'>Git</p>
            </div>
          </div>
        </section>

        <section className='min-h-screen text-center pb-20'>
          <h3 className='text-2xl md:py-5 md:pt-10 md:text-4xl dark:text-gray-200'>
            Favorite Projects
          </h3>
          <div className='grid grid-cols-1 lg:grid-cols-3 lg:gap-10 lg:gap-y-0'>
            <div className='text-center shadow-lg p-10 rounded-xl mt-10 bg-slate-700 flex-1'>
              <h3 className='text-xl font-bold pb-2 md:pb-5 text-slate-50'>procrastiNOT</h3>
              <div className='flex gap-3 justify-center flex-wrap pb-2 md:pb-4'>
                <h4 className='text-lg font-medium px-2 text-amber-200 border-solid border-2 border-amber-200 rounded-lg hover:cursor-default hover:border-amber-200 hover:border-solid'>
                  Congressional App Challenge 2021 IL-07 Winner
                </h4>
              </div>
              <div className='flex gap-3 justify-center flex-wrap md:pb-2'>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>Python</h4>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>SwiftUI</h4>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>JS</h4>
              </div>
              <p className='text-slate-200 py-2'>
                An assignment prioritizer and scheduler that uses inputs from Aspen, Google Classroom,
                and Google Calendar to help students prevent procrastination.
              </p>
              <div className='flex gap-3 justify-center md:pt-2'>
                <a target="_blank" href="https://www.congressionalappchallenge.us/21-IL07/" rel="noopener noreferrer">
                  <div className='flex gap-2 justify-center text-lg font-medium px-2 text-slate-50 border-solid border-2 border-slate-500 bg-slate-500 rounded-lg hover:cursor-pointer hover:border-slate-50 hover:border-solid items-center'>
                    <BsLink45Deg />
                    <h1>Read More</h1>
                  </div>
                </a>
              </div>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl mt-10 bg-slate-700 flex-1'>
              <h3 className='text-xl font-bold pb-2 md:pb-5 text-slate-50'>MetroSafe</h3>
              <div className='flex gap-3 justify-center flex-wrap pb-2 md:pb-4'>
                <h4 className='text-lg font-medium px-2 text-amber-200 border-solid border-2 border-amber-200 rounded-lg hover:cursor-default hover:border-amber-200 hover:border-solid'>
                  CodeDay: Most Useful App
                </h4>
              </div>
              <div className='flex gap-3 justify-center flex-wrap md:pb-2'>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>SwiftUI</h4>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>Firebase</h4>
              </div>
              <p className='text-slate-200 py-2'>
                A public safety app that protects residents of urban communities by
                providing crowdsourced information about crime and violence close to them.
              </p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl mt-10 bg-slate-700 flex-1'>
              <h3 className='text-xl font-bold pb-2 md:pb-5 text-slate-50'>Stock Trading Assistant</h3>
              <div className='flex gap-3 justify-center flex-wrap pb-2 md:pb-4'>
                <h4 className='text-lg font-medium px-2 text-amber-200 border-solid border-2 border-amber-200 rounded-lg hover:cursor-default hover:border-amber-200 hover:border-solid'>
                  CodeDay: Best in Class App
                </h4>
              </div>
              <div className='flex gap-3 justify-center flex-wrap md:pb-2'>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>Python</h4>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>Yahoo Finance</h4>
              </div>
              <p className='text-slate-200 py-2'>
                A trading assistant that eases the transaction process for beginner
                investors by providing them with investing tools and explaining terms such as “stop loss.”
              </p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl mt-10 bg-slate-700 flex-1'>
              <h3 className='text-xl font-bold pb-2 md:pb-5 text-slate-50'>Modeling Vaccinations</h3>
              <div className='flex gap-3 justify-center flex-wrap pb-2 md:pb-4'>
                <h4 className='text-lg font-medium px-2 text-amber-200 border-solid border-2 border-amber-200 rounded-lg hover:cursor-default hover:border-amber-200 hover:border-solid'>
                  MTFC: 2021 Semi-finalist
                </h4>
              </div>
              <div className='flex gap-3 justify-center flex-wrap md:pb-2'>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>Python</h4>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>Excel</h4>
              </div>
              <p className='text-slate-200 py-2'>
                Co-authored &quot;Distribution of the COVID-19 Vaccine to Minimize Cases in Chicago&quot;
                to model the ideal distribution of the COVID-19 vaccines in Chicago.
              </p>
              <div className='flex gap-3 justify-center md:pt-2'>
                <a target="_blank" href="vaccinePaper.pdf" download="Distribution of the COVID-19 Vaccine to Minimize Cases in Chicago" rel="noopener noreferrer">
                  <div className='flex gap-2 justify-center text-lg font-medium px-2 text-slate-50 border-solid border-2 border-slate-500 bg-slate-500 rounded-lg hover:cursor-pointer hover:border-slate-50 hover:border-solid items-center'>
                    <MdOutlineArticle />
                    <h1>Paper</h1>
                  </div>
                </a>
                <a target="_blank" href="https://github.com/aviral-mehrotra/COVID-19_Vaccine_Distribution_Plan" rel="noopener noreferrer">
                  <div className='flex gap-2 justify-center text-lg font-medium px-2 text-slate-50 border-solid border-2 border-slate-500 bg-slate-500 rounded-lg hover:cursor-pointer hover:border-slate-50 hover:border-solid items-center'>
                    <BsLink45Deg />
                    <h1>Code</h1>
                  </div>
                </a>
              </div>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl mt-10 bg-slate-700 flex-1'>
              <h3 className='text-xl font-bold pb-2 md:pb-5 text-slate-50'>Photovoltaic Systems</h3>
              <div className='flex gap-3 justify-center flex-wrap pb-2 md:pb-4'>
                <h4 className='text-lg font-medium px-2 text-amber-200 border-solid border-2 border-amber-200 rounded-lg hover:cursor-default hover:border-amber-200 hover:border-solid'>
                  MTFC: 2022 Semi-finalist
                </h4>
              </div>
              <div className='flex gap-3 justify-center flex-wrap md:pb-2'>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>Excel</h4>
              </div>
              <p className='text-slate-200 py-2'>
                Co-authored &quot;Feasibility of Photovoltaic Energy System to Power Remote Home&quot;
                to model the optimal battery energy storage system (BESS) for buildings.
              </p>
              <div className='flex gap-3 justify-center md:pt-2'>
                <a target="_blank" href="energyPaper.pdf" download="Feasibility of Photovoltaic Energy System to Power Remote Home" rel="noopener noreferrer">
                  <div className='flex gap-2 justify-center text-lg font-medium px-2 text-slate-50 border-solid border-2 border-slate-500 bg-slate-500 rounded-lg hover:cursor-pointer hover:border-slate-50 hover:border-solid items-center'>
                    <MdOutlineArticle />
                    <h1>Paper</h1>
                  </div>
                </a>
              </div>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl mt-10 bg-slate-700 flex-1'>
              <h3 className='text-xl font-bold pb-2 md:pb-5 text-slate-50'>WordLeap</h3>
              <div className='flex gap-3 justify-center flex-wrap pb-2 md:pb-4'>
                <h4 className='text-lg font-medium px-2 text-sky-200 border-solid border-2 border-sky-200 rounded-lg hover:cursor-default hover:border-sky-200 hover:border-solid'>
                  Internship
                </h4>
              </div>
              <div className='flex gap-3 justify-center flex-wrap md:pb-2'>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>React</h4>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>Python</h4>
              </div>
              <p className='text-slate-200 py-2'>
                An in-context translation API that helps non-native English speakers better understand content.
                React was used to create components to help users navigate the app. 
              </p>
              <div className='flex gap-3 justify-center md:pt-2'>
                <a target="_blank" href="https://github.com/aviral-mehrotra/wordleap-onboarding-work" rel="noopener noreferrer">
                  <div className='flex gap-2 justify-center text-lg font-medium px-2 text-slate-50 border-solid border-2 border-slate-500 bg-slate-500 rounded-lg hover:cursor-pointer hover:border-slate-50 hover:border-solid items-center'>
                    <BsLink45Deg />
                    <h1>Code</h1>
                  </div>
                </a>
              </div>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl mt-10 bg-slate-700 flex-1'>
              <h3 className='text-xl font-bold pb-2 md:pb-5 text-slate-50'>Fermilab TARGET</h3>
              <div className='flex gap-3 justify-center flex-wrap pb-2 md:pb-4'>
                <h4 className='text-lg font-medium px-2 text-sky-200 border-solid border-2 border-sky-200 rounded-lg hover:cursor-default hover:border-sky-200 hover:border-solid'>
                  Internship
                </h4>
              </div>
              <div className='flex gap-3 justify-center flex-wrap md:pb-2'>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>Python</h4>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>FPGA</h4>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>CNNs</h4>
              </div>
              <p className='text-slate-200 py-2'>
              A computer vision project using a Pynq-Z2 board, hls4ml, CNNs, FPGAs, and Python
              that was incorporated into Fermilab&apos;s hls4ml Demo Lab at DEFCON 30.
              </p>
              <div className='flex gap-3 justify-center md:pt-2'>
                <a target="_blank" href="fermilab_hls4ml_slides.pdf" download="Fermilab hls4ml Presentation" rel="noopener noreferrer">
                  <div className='flex gap-2 justify-center text-lg font-medium px-2 text-slate-50 border-solid border-2 border-slate-500 bg-slate-500 rounded-lg hover:cursor-pointer hover:border-slate-50 hover:border-solid items-center'>
                    <BsLink45Deg />
                    <h1>Read More</h1>
                  </div>
                </a>
              </div>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl mt-10 bg-slate-700 flex-1'>
              <h3 className='text-xl font-bold pb-2 md:pb-5 text-slate-50'>Natural Disaster Tracker</h3>
              <div className='flex gap-3 justify-center flex-wrap pb-2 md:pb-4'>
                <h4 className='text-lg font-medium px-2 text-amber-200 border-solid border-2 border-amber-200 rounded-lg hover:cursor-default hover:border-amber-200 hover:border-solid'>
                  NASA Space Apps: Chicago Winner & Global Qualifier
                </h4>
              </div>
              <div className='flex gap-3 justify-center flex-wrap md:pb-2'>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>SwiftUI</h4>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>Firebase</h4>
              </div>
              <p className='text-slate-200 py-2'>
                A mobile app that combines NASA&apos;s live stream of natural disasters and crowdsourcing
                to predict and display the route of natural disasters.
              </p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl mt-10 bg-slate-700 flex-1'>
              <h3 className='text-xl font-bold pb-2 md:pb-5 text-slate-50'>Kickstarter Fraud</h3>
              <div className='flex gap-3 justify-center flex-wrap pb-2 md:pb-4'>
                <h4 className='text-lg font-medium px-2 text-sky-200 border-solid border-2 border-sky-200 rounded-lg hover:cursor-default hover:border-sky-200 hover:border-solid'>
                  Research
                </h4>
              </div>
              <div className='flex gap-3 justify-center flex-wrap md:pb-2'>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>Blockchain</h4>
              </div>
              <p className='text-slate-200 py-2'>
                Researching with a University of Waterloo Ph.D. candidate to implement
                blockchain technologies to identify fraudulent Kickstarter campaigns

              </p>
              <div className='flex gap-3 justify-center md:pt-2'>
                <a target="_blank" href="energyPaper.pdf" download="Feasibility of Photovoltaic Energy System to Power Remote Home" rel="noopener noreferrer">
                  <div className='flex gap-2 justify-center text-lg font-medium px-2 text-slate-50 border-solid border-2 border-slate-500 bg-slate-500 rounded-lg hover:cursor-pointer hover:border-slate-50 hover:border-solid items-center'>
                    <MdOutlineArticle />
                    <h1>Coming Soon</h1>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </section>

        <section className='text-center bg-zinc-600 pb-8 md:pb-12 rounded-xl'>
          <h3 className='text-2xl pt-5 pb-2 md:py-5 md:pt-10 md:text-4xl text-slate-50 dark:text-gray-200'>
            Let&apos;s collaborate!
          </h3>
          <p className='text-slate-200 pt-2 pb-5 px-2 md:pb-4'>
            If you&apos;re interested in working with me on a research project, competition,
            or other project, feel free to email me and we can begin.
          </p>
          <div className='flex gap-3 justify-center md:pt-2'>
            <a href="mailto:aviral.mehrotra@gmail.com" rel="noopener noreferrer">
              <div className='flex gap-2 justify-center text-lg font-medium px-2 text-slate-50 border-solid border-2 border-gray-500 bg-gray-500 rounded-lg hover:cursor-pointer hover:border-slate-50 hover:border-solid items-center'>
                <AiFillMail />
                <h1>Email Me</h1>
              </div>
            </a>
          </div>
        </section>

        <section className='min-h-screen text-center pt-10'>
          <h3 className='text-2xl md:py-5 md:pt-10 md:text-4xl dark:text-gray-200'>
            Other Noteworthy Work
          </h3>
          <div className='grid grid-cols-1 lg:grid-cols-3 lg:gap-10 lg:gap-y-0'>
            <div className='text-center shadow-lg p-10 rounded-xl mt-10 bg-slate-700 flex-1'>
              <h3 className='text-xl font-bold pb-2 md:pb-5 text-slate-50'>Prophecy</h3>
              <div className='flex gap-3 justify-center flex-wrap md:pb-2'>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>Python</h4>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>XGBoost</h4>
              </div>
              <p className='text-slate-200 py-2'>
                A daily stock price predictor that uses an XGBoost regression model.
                This model was used due to its ability to work with large datasets and its customizability.
              </p>
              <div className='flex gap-3 justify-center md:pt-2'>
                <a target="_blank" href="https://github.com/aviral-mehrotra/Prophecy" rel="noopener noreferrer">
                  <div className='flex gap-2 justify-center text-lg font-medium px-2 text-slate-50 border-solid border-2 border-slate-500 bg-slate-500 rounded-lg hover:cursor-pointer hover:border-slate-50 hover:border-solid items-center'>
                    <BsLink45Deg />
                    <h1>Code</h1>
                  </div>
                </a>
              </div>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl mt-10 bg-slate-700 flex-1'>
              <h3 className='text-xl font-bold pb-2 md:pb-5 text-slate-50'>EasyFood</h3>
              <div className='flex gap-3 justify-center flex-wrap md:pb-2'>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>SwiftUI</h4>
              </div>
              <p className='text-slate-200 py-2'>
                An app that connects restaurants that often have remaining food at the end of the day that would otherwise
                be wasted with underprivileged people that can benefit from an increased access to cheap but nutritious food.
              </p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl mt-10 bg-slate-700 flex-1'>
              <h3 className='text-xl font-bold pb-2 md:pb-5 text-slate-50'>Recycleopedia</h3>
              <div className='flex gap-3 justify-center flex-wrap md:pb-2'>
                <h4 className='text-lg font-medium px-2 text-cyan-400 border-solid border-2 bg-cyan-800 border-cyan-800 rounded-lg hover:cursor-default hover:border-cyan-400 hover:border-solid'>SwiftUI</h4>
              </div>
              <p className='text-slate-200 py-2'>
                Recycling Encyclopedia: A mobile app that increases and improves recycling
                by providing users with explanations of what products can and cannot be recycled.
              </p>
              <div className='flex gap-3 justify-center md:pt-2'>
                <a target="_blank" href="" rel="noopener noreferrer">
                  <div className='flex gap-2 justify-center text-lg font-medium px-2 text-slate-50 border-solid border-2 border-slate-500 bg-slate-500 rounded-lg hover:cursor-pointer hover:border-slate-50 hover:border-solid items-center'>
                    <GrAppleAppStore />
                    <h1>Coming Soon</h1>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </section>

        <section className='text-center bg-zinc-600 -mx-40 px-40'>
          <div className='grid grid-cols-1 lg:grid-cols-2 gap-5 lg:gap-10 lg:gap-y-0 py-2 md:py-5'>
            <h1 className='text-2xl md:text-3xl md:-ml-48 text-slate-200 dark:text-slate-200'>
              aviral
              <span className="text-zinc-500 dark:text-zinc-400">
                mehrotra
              </span>
            </h1>
            <div className='grid md:grid-cols-4 gap-3 justify-center pb-2 md:pb-0'>
              <a target="_blank" href="https://github.com/aviral-mehrotra" rel="noopener noreferrer">
                <div className='flex gap-2 justify-center text-lg font-medium px-2 text-slate-50 border-solid border-2 border-gray-500 bg-gray-500 rounded-lg hover:cursor-pointer hover:border-slate-50 hover:border-solid items-center'>
                  <AiFillGithub />
                  <h1>Github</h1>
                </div>
              </a>
              <a target="_blank" href="https://www.linkedin.com/in/aviralmehrotra" rel="noopener noreferrer">
                <div className='flex gap-2 justify-center text-lg font-medium px-2 text-slate-50 border-solid border-2 border-gray-500 bg-gray-500 rounded-lg hover:cursor-pointer hover:border-slate-50 hover:border-solid items-center'>
                  <AiFillLinkedin />
                  <h1>LinkedIn</h1>
                </div>
              </a>
              <a href="mailto:aviral.mehrotra@gmail.com" rel="noopener noreferrer">
                <div className='flex gap-2 justify-center text-lg font-medium px-2 text-slate-50 border-solid border-2 border-gray-500 bg-gray-500 rounded-lg hover:cursor-pointer hover:border-slate-50 hover:border-solid items-center'>
                  <AiFillMail />
                  <h1>Email</h1>
                </div>
              </a>
              <a href="resume.pdf" download="Aviral Mehrotra's Resume" rel="noopener noreferrer">
                <div className='flex gap-2 justify-center text-lg font-medium px-2 text-slate-50 border-solid border-2 border-gray-500 bg-gray-500 rounded-lg hover:cursor-pointer hover:border-slate-50 hover:border-solid items-center'>
                  <MdArticle />
                  <h1>Resume</h1>
                </div>
              </a>
            </div>
          </div>
        </section>

      </main>
    </div>
  )
}
